import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { Router, useRouter } from 'next/router'
import { useEffect, useState } from 'react';
import { banners } from '../assets';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter();
  const [keys, setKeys] = useState('');
  const [collection, setCollection] = useState([]);
  const [collection2, setCollection2] = useState([]);

  const getDataBanner = () => {
    axios.get(`http://localhost:4000/banners`).then(
      res => {
        console.log(res.data)
        const collection = res.data;
        setCollection(collection);
      }
    )
  }

  const SendIdDonasi = (id) => {
    localStorage.setItem('donasiKey', id);
  }

  const getDataDonasiValid = () => {
    axios.get(`http://localhost:4000/donasis/valid`).then(
      res => {
        const collection2 = res.data;
        console.log(collection2);
        setCollection2(collection2)
      }
    )
  }

  const getId = () => {
    var idKey = localStorage.getItem('idKey')
    var keys = idKey;
    setKeys(keys)
    console.log(keys)
  }

  useEffect(() => {
    getId();
    getDataBanner();
    getDataDonasiValid();
  }, [])

  return (
    <div>
      <Head>
        <title>Ikhlas Bantu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type='image/x-icon' href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </Head>

      <div>
        <Navbar beranda />

        <div className='container' style={{ paddingBottom: 50 }}>
          {/* Start Carousel */}
          <div style={{ paddingTop: 20 }}>
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-indicators">
                {
                  collection.map((res, i) => (
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to={i} className={i == 0 ? "active" : ""} aria-current={i == 0 ? "true" : "false"} aria-label={"Slide " + (i + 1)}></button>
                  ))
                }
                {/* <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button> */}
              </div>
              <div class="carousel-inner">
                {
                  collection.map((res, i) => (
                    <div className={"carousel-item " + (i == 0 ? "active" : "")} key={i}>
                      <img src={`http://localhost:4000/resources/uploads/${res.gambar}`} className={"d-block w-100 " + styles.sizeHeight} alt="..." />
                      <div class="carousel-caption d-none d-md-block">
                        {/* <h5>{res.judul}</h5>
                        <p>{res.deskripsi}</p> */}
                      </div>
                    </div>
                  ))
                }
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          </div>
          {/* End Carousel */}

          {/* Start Donasi Terkini */}
          <div className={styles.donasiTop}>
            <h2 style={{ fontWeight: 'bold' }}><u>Donasi Terkini</u></h2>
            <div className='container'>
              <div className='row'>
                {
                  collection2.reverse().map((res, i) => i < 9 ? (
                    <div className='col-md-4' key={i}>
                      <div className={styles.boxDonasi}>
                        <img src={`http://localhost:4000/resources/uploads/${res.foto}`} className={styles.imgPosition} />
                        <h5>{res.judul}</h5>
                        <div>
                          <p>Dana Terkumpul : {res.terkumpul}</p>
                          <p>Rp. {res.target}</p>
                        </div>
                        <div className={styles.btnWidth}>
                          <Link href={`/donasi/detail-donasi?id=${res._id}`}>
                            <button onClick={()=>SendIdDonasi(res._id)} className={'btn btn-outline-success ' + styles.btnWidth} >Donasi</button>
                          </Link>
                        </div>
                      </div>
                    </div>
                  ) : null)
                }
                {/* <div className='col-4'>
                  <div className={styles.boxDonasi}>
                    <img className={styles.imgPosition} />
                    <h5>Bantuan Erupsi Gunung Semeru</h5>
                    <div>
                      <p>Dana Terkumpul : </p>
                      <p>Rp. 101.500.000</p>
                    </div>
                    <div className={styles.btnWidth}>
                      <button className={'btn btn-outline-success ' + styles.btnWidth}>Donasi</button>
                    </div>
                  </div>
                </div>
                <div className='col-4'>
                  <div className={styles.boxDonasi}>
                    <img className={styles.imgPosition} />
                    <h5>Sedekah Spesial Jum'at</h5>
                    <div>
                      <p>Dana Terkumpul : </p>
                      <p>Rp. 101.500.000</p>
                    </div>
                    <div className={styles.btnWidth}>
                      <button className={'btn btn-outline-success ' + styles.btnWidth}>Donasi</button>
                    </div>
                  </div>
                </div>
                <div className='col-4'>
                  <div className={styles.boxDonasi}>
                    <img className={styles.imgPosition} />
                    <h5>Bantu Kanker Ibu Siti</h5>
                    <div>
                      <p>Dana Terkumpul : </p>
                      <p>Rp. 101.500.000</p>
                    </div>
                    <div className={styles.btnWidth}>
                      <button className={'btn btn-outline-success ' + styles.btnWidth}>Donasi</button>
                    </div>
                  </div>
                </div> */}
              </div>
            </div>
          </div>
          {/* End Donasi Terkini */}

          {/* Start Instagram */}
          <div>
            
          </div>
          {/* Start Harapan Kami */}
          {/* <div className={styles.harapanTop}>
            <h2 style={{ fontWeight: 'bold' }}><u>Harapan Kami</u></h2>
            <div className={styles.boxHarapan}>
              <div className='container'>
                <div className='row'>
                  <div className='col-1'>
                    <img className={styles.imgProfile} />
                  </div>
                  <div className={'col-2 ' + styles.marginProfile}>
                    <p>Rita Kurnia <br /> Pada 09.45</p>
                  </div>
                  <div className={'col ' + styles.marginProfileStatus}>
                    <p>"Semoga selalu diberikan kesehatan dan diberkati setiap harinya"</p>
                    <hr />
                  </div>
                </div>

                <div className='row'>
                  <div className='col-1'>
                    <img className={styles.imgProfile} />
                  </div>
                  <div className={'col-2 ' + styles.marginProfile}>
                    <p>Rita Kurnia <br /> Pada 09.45</p>
                  </div>
                  <div className={'col ' + styles.marginProfileStatus}>
                    <p>"Semoga selalu diberikan kesehatan dan diberkati setiap harinya"</p>
                    <hr />
                  </div>
                </div>

                <div className='row'>
                  <div className='col-1'>
                    <img className={styles.imgProfile} />
                  </div>
                  <div className={'col-2 ' + styles.marginProfile}>
                    <p>Rita Kurnia <br /> Pada 09.45</p>
                  </div>
                  <div className={'col ' + styles.marginProfileStatus}>
                    <p>"Semoga selalu diberikan kesehatan dan diberkati setiap harinya"</p>
                    <hr />
                  </div>
                </div>

                <div className='row'>
                  <div className='col-1'>
                    <img className={styles.imgProfile} />
                  </div>
                  <div className={'col-2 ' + styles.marginProfile}>
                    <p>Rita Kurnia <br /> Pada 09.45</p>
                  </div>
                  <div className={'col ' + styles.marginProfileStatus}>
                    <p>"Semoga selalu diberikan kesehatan dan diberkati setiap harinya"</p>
                    <hr />
                  </div>
                </div>

                <div className='row'>
                  <div className='col-1'>
                    <img className={styles.imgProfile} />
                  </div>
                  <div className={'col-2 ' + styles.marginProfile}>
                    <p>Rita Kurnia <br /> Pada 09.45</p>
                  </div>
                  <div className={'col ' + styles.marginProfileStatus}>
                    <p>"Semoga selalu diberikan kesehatan dan diberkati setiap harinya"</p>
                    <hr />
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.rightSide}>
              <Link href={keys == null ? '/login' : '/donasi'}>
                <button className={'btn btn-outline-primary ' + styles.btnWidth}>+ Buat Harapan</button>
              </Link>
            </div>
          </div> */}
          {/* End Harapan Kami */}
        </div>

        <Footer />
      </div>
    </div>
  )
}
